import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "./components/QueryProvider";
import { ThemeProvider } from "./components/ThemeProvider";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import { Toaster } from "./components/ui/Toaster";
import { Toaster as Sonner } from "./components/ui/Sonner";
import Header from "./components/layout/Header";
import { Footer } from "react-day-picker";
import FixedFooter from "./components/layout/FixedFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <QueryProvider>
            <ThemeProvider defaultTheme="light" storageKey="ui-theme">
              <TooltipProvider>
                <Toaster />
                <Sonner />
                <div className="flex flex-col min-h-screen bg-background">
                  <Header />
                  <main className="flex-grow">
                    {children}
                  </main>
                  <Footer />
                  <FixedFooter />
              </div>
              </TooltipProvider>
            </ThemeProvider>
          </QueryProvider>
      </body>
    </html>
  );
}
